--[[
Doable Asset Library
|| Asset library, allowing for modular
|| and synced assets

REQUIRES:
doable.doable_utils
doable.player_config


FULL EXAMPLE USAGE

(Make sure to create a separate
lua file in your avatar folder.
Don't just edit this library.)

---
require("doable.doable_assetlib")

local SLOTID = {
    stackable_prop_emote = 1,
    major_emote = 2,
    head = 3,
    hat = 4,
}

DoableAssetManager
    -- Creates asset at slot id defined in table above,
    -- with asset id 1
    :CreateAsset(SLOTID.head, 1)

    -- Sets what model parts are managed by this asset
    :setModelParts({
        models.main.Head.Glasses
    })

    -- Sets action wheel display name and item
    :setDisplay("Glasses", "minecraft:glass_pane")

    -- Hides model parts of an asset on startup
    :enable(false)

require("libs.do_assetlib_loop")
local wheel = require("libs.doable_assetlib_wheel")

action_wheel:setPage(wheel.CreateActionWheelPage())

---

]] --


require('doable.doable_utils')
local DoableConfig = require('doable.doable_player_config')

local no_outfit = "_"

-- available cached callbacks:
-- on_pet
DoableCallbacksCache = {
    on_pet = {},
    on_toggle = {}
}

--- Optional texture item of an outfit.
--- @class DoableTextureItem
--- @field create fun(texture_name):DoableTextureItem

--- @type DoableTextureItem
DoableTextureItem = Class()

---@param texture Texture
function DoableTextureItem:create(texture)
    local texture_item = setmetatable({}, self)
    return texture_item
end

--------

--- Asset (stored in slot)
--- @class DoableAsset
--- @field currently_active boolean
--- @field name string
--- @field slot_name string
--- @field model_parts table<ModelPart>
--- @field display_item string
--- @field display_text string
--- @field save boolean
--- @field callbacks table<string, function>
--- @field persistent_animations table<Animation>
--- @field setDisplay fun(self, display_text, display_item):DoableAsset
--- @field create fun(name, slot_name):DoableAsset
--- @field enable fun(self, state):DoableAsset
--- @field setModelParts fun(...):DoableAsset
--- @field setAnimations fun(...):DoableAsset
--- @field setOnPet fun(self, on_pet_callback):DoableAsset
--- @field setNeverSaveToConfig fun(self):DoableAsset

--- @type DoableAsset
DoableAsset = Class()

--- DO NOT CALL it manually.
function DoableAsset:create(name, slot_name)
    local asset = setmetatable({
        currently_active = true,
        slot_name = slot_name,
        display_item = "minecraft:glass_pane",
        display_text = "UNKNOWN",
        name = name,
        persistent_animations = {},
        model_parts = {},
        save = true,
        callbacks = {},
    }, self)
    return asset
end

--- Enables or disables an asset's model parts,
--- visibly hiding the model parts.
---
--- ## USAGE:
--- Use only on asset creation, else
--- there will be a desync.
---
--- ## EXAMPLE:
---
--- asset:enable(false)
function DoableAsset:enable(state)
    if self.model_parts == nil then return self end
    for _, model_part in ipairs(self.model_parts) do
        model_part:setVisible(state)
    end
    return self
end

--- Sets display text, display item
--- for an asset in action wheel generated by doable_assetlib_wheel.lua
---
--- ## USAGE:
--- Use only an asset creation.
function DoableAsset:setDisplay(display_text, display_item)
    self.display_item = display_item
    self.display_text = display_text
    return self
end

--- Sets model parts this asset will
--- manage. Best to use unique model parts
--- that aren't managed in any other way,
--- except by DoableAssetLib.
---
--- ## USAGE:
--- Use only on asset creation.
---
--- ## EXAMPLE:
---
--- asset:setModelParts({models.my_model.BestPart, models.my_model.Head})
function DoableAsset:setModelParts(...)
    self.model_parts = ...
    return self
end

--- Sets a callback that happens when the
--- asset is toggled on or off.
---
--- ## USAGE:
--- Use only on asset creation.
---
--- ## EXAMPLE:
---
--- asset:setOnToggle(function (self, toggleState)
--- print(toggleState)
--- end)
function DoableAsset:setOnToggle(on_toggle_callback)
    DoableCallbacksCache.on_toggle[tostring(self.name)] = true
    self.callbacks.on_toggle = on_toggle_callback
    return self
end

--- Sets persistent animations that get
--- enabled or disabled when the asset
--- is enabled or disabled.
---
--- ## USAGE:
--- Use only on asset creation.
---
--- ## EXAMPLE:
--- asset:setAnimations({animations.my_model.Dance, animations.my_model.Jump})
function DoableAsset:setAnimations(...)
    self.persistent_animations = ...
    return self
end

--- Sets what happens when host is
--- being pat if you have a compatible pat script
---
--- ## USAGE:
---
--- For example, with AuriaPat, ensure
--- DoableCallCallbacks("on_pet") is placed
--- inside AuriaPat's local playerEvents table:
---
--- oncePat = {
---   --function(entity) end
---   function(isPetted)
---      DoableCallCallbacks("on_pet")
---   end
---}
---
--- With other PatPat type of scripts, generally,
--- ensure DoableCallCallbacks("on_pet") is called
--- once per pat.
---
--- ## EXAMPLE:
---
--- asset:setOnPet(function (self) print("yes") end)
function DoableAsset:setOnPet(on_pet_callback)
    DoableCallbacksCache.on_pet[tostring(self.name)] = true
    self.callbacks.on_pet = on_pet_callback
    return self
end

--- Marks asset as not save-able to config.
---
--- ## USAGE:
--- Use on asset creation only.
---
--- ## EXAMPLE:
--- asset:setNeverSaveToConfig()
function DoableAsset:setNeverSaveToConfig()
    self.save = false
    return self
end

--------

--- Slot (stores assets)
--- @class DoableSlot
--- @field force_update boolean
--- @field asset string
--- @field setAsset fun(self, asset_name):DoableSlot
--- @field create fun():DoableSlot

--- @type DoableSlot
DoableSlot = Class()

function DoableSlot:create()
    ---@type DoableSlot
    local slot = setmetatable({
        force_update = false,
        asset = nil,
    }, self)
    return slot
end

--- @param new_asset_name string
function DoableSlot:setAsset(new_asset_name)
    self.asset = new_asset_name

    return self
end

--------

--- Manages assets.
--- @class DoableAssetManager
--- @field Assets table<string, DoableAsset>
--- @field CreateAsset fun(self, slot_name, assetName):DoableAsset

--- @type DoableAssetManager
DoableAssetManager = Class()
DoableAssetManager.Assets = {}

--- Creates an asset
---
--- ## USAGE
--- Use if you want to create an asset.
--- Best to use short IDs for smaller pings!
---
--- ## EXAMPLE:
--- If slot name is 1 and asset id is 2 go about it like:
--- DoableAssetManager:createAsset(1, 2)
function DoableAssetManager:CreateAsset(slot_name, asset_id)
    local asset = DoableAsset:create(tostring(asset_id), tostring(slot_name))
    rawset(self.Assets, tostring(asset_id), asset)
    return asset
end

--- Manages slots.
--- @class DoableSlotManager
--- @field Slots table<string, DoableSlot>
--- @field LoadAllFromConfig fun(self):DoableSlotManager
--- @field saveSlotToConfig fun(self, slot_name):DoableSlotManager
--- @field markForUpdate fun(self, slot_name):DoableSlotManager
--- @field markAllForUpdate fun(self):DoableSlotManager

--- @type DoableSlotManager
DoableSlotManager = Class()
DoableSlotManager.Slots = setmetatable({}, {
    __index = function(self, slot_name)
        local subtable = DoableSlot:create()
        rawset(self, tostring(slot_name), subtable)
        return subtable
    end
})

function DoableSlotManager:saveSlotToConfig(slot_name, asset_name)
    local old_config_name = config:getName()
    config:setName("DoableAssetLib_" .. DoableConfig.DoableConfig.config_basename)

    if asset_name == nil then
        asset_name = no_outfit
    end

    config:save(
        slot_name,
        asset_name
    )
    config:setName(old_config_name)
    return self
end

function DoableSlotManager:LoadAllFromConfig()
    local old_config_name = config:getName()
    config:setName("DoableAssetLib_" .. DoableConfig.DoableConfig.config_basename)

    for slot_name, outfit in pairs(config:load()) do
        if outfit == no_outfit then
            outfit = nil
        end

        local slot_name = tostring(slot_name)
        local outfit = tostring(outfit)

        self.Slots[slot_name].force_update = true
        self.Slots[slot_name]:setAsset(outfit)
    end

    config:setName(old_config_name)
    return self
end

function DoableCallCallbacks(callback_name)
    if DoableCallbacksCache[callback_name] == nil then return end

    for slot_name, slot in pairs(DoableSlotManager.Slots) do
        if slot.asset ~= nil then
            if DoableCallbacksCache[callback_name][slot.asset] ~= nil then
                local asset = DoableAssetManager.Assets[slot.asset]

                pcall(asset.callbacks[callback_name], asset)
            end
        end
    end
end

